name: Basic CI

on: 
  push:
    branches: [ develop ]
jobs:
  build:
    runs_on: ubuntu_latest
    steps: 
      - uses: actions/checkout@v4
      - name: Run build
        run: echo "CI is running"